### ISSUE TITLE
Add system math 

### ISSUE THREAD

**Issue by DylanBozarth** [DylanBozarth/untitled-space-game#43]
Calculate system power based of off ships and buildings. 
Probably going to have to wait until we add the ships.

**Comment by PaulMasonDev** [comment]
We could code it in such a way that the ship power is a random number (give me a range) and then all we have to do when ships are figured out is hook it all up. Is getting the the system power going blocking anything else?

**Comment by DylanBozarth** [comment]
Right now let's just say that each ship gives 1 power, we can do balancing later. And I also think we can just have 1 basic type of ship for now

**Comment by PaulMasonDev** [comment]
@DylanBozarth About to start this one, so is the Hanger 700 referring to the ship-based power contribution? The planetary defenses, the building contribution? Or are those two separate from "System Power" which doesn't have a value next to it (looks like its a title).

**Comment by DylanBozarth** [comment]
Ideally it would show the amount of power that came from ships and the amount of power that came from buildings. 
System power will be the total, the sum of the hangar and buildings

**Comment by PaulMasonDev** [comment]
Got it
